# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_m_cov <- function(data_0, data_1, X, nu_vec, sigma) {
    .Call('_BGCR_compute_m_cov', PACKAGE = 'BGCR', data_0, data_1, X, nu_vec, sigma)
}

